name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 20
    strategy:
      matrix:
        platform: [ubuntu-latest]  # 先单平台测试
        include:
          - platform: ubuntu-latest
            rid: linux-x64
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore --runtime ${{ matrix.rid }}

    - name: Publish
      run: dotnet publish SCSA/SCSA.csproj -c Release -r ${{ matrix.rid }} -o publish/${{ matrix.rid }}

    - name: Zip artifacts
      shell: bash
      run: |
        cd publish/${{ matrix.rid }}
        zip -r ../${{ matrix.rid }}.zip ./*
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.rid }}
        path: publish/${{ matrix.rid }}.zip
