name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            rid: linux-x64
          - platform: ubuntu-latest
            rid: linux-arm64
          - platform: windows-latest
            rid: win-x64
          - platform: windows-latest
            rid: win-arm64
          - platform: macos-latest
            rid: osx-x64
          - platform: macos-latest
            rid: osx-arm64
    runs-on: ${{ matrix.platform }}

    env:
      FILE_VERSION: ${{ github.ref_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore SCSA/SCSA.csproj --runtime ${{ matrix.rid }}

    - name: Publish
      run: |
        dotnet publish SCSA/SCSA.csproj -c Release -r ${{ matrix.rid }} --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish
        cd publish
        ZIP_NAME=SCSA-${{ matrix.rid }}-${FILE_VERSION}.zip
        if [ "$RUNNER_OS" == "Windows" ]; then
          powershell -Command "Compress-Archive -Path * -DestinationPath ../$ZIP_NAME"
        else
          zip -r ../$ZIP_NAME ./*
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.rid }}-binary
        path: SCSA-${{ matrix.rid }}-${{ env.FILE_VERSION }}.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: '*-binary'

    - name: Verify files
      run: find artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: artifacts/*/*.zip
        body: |
          feat: Optimize Data Length Restrictions in Software Trigger Mode

          ## 🚀 New Features
          
          ### Software Trigger Mode Data Length Optimization
          - **Range Restriction**: Limited data length to 2048-16777216 range in software trigger mode
          - **Power of 2 Validation**: Ensured data length must be a power of 2 for optimal performance
          - **Auto-Adjustment**: Implemented automatic adjustment to nearest valid value when user input is invalid
          - **Smart UI Hints**: Added orange hint text to inform users about data length requirements
          
          ### User Experience Improvements
          - **Real-time Validation**: Automatic validation during trigger type switching, initialization, and manual modification
          - **Visual Feedback**: Clear visual indicators for data length constraints
          - **Seamless Adjustment**: Transparent value correction without disrupting user workflow
          
          ## 🔧 Technical Improvements
          - **Helper Functions**: Added utility functions for power-of-2 calculations (IsPowerOfTwo, GetLowerPowerOfTwo, GetNextPowerOfTwo)
          - **Reactive Validation**: Implemented reactive property subscriptions for real-time constraint enforcement
          - **UI Enhancement**: Updated settings view layout to accommodate hint display
          
          ## 📚 Documentation
          - **Parameter Constraints**: Clear documentation of data length limitations in software trigger mode
          - **User Guidance**: Improved user interface with contextual hints and validation feedback
