name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            rid: linux-x64
          - platform: ubuntu-latest
            rid: linux-arm64
          - platform: windows-latest
            rid: win-x64
          - platform: windows-latest
            rid: win-arm64
          - platform: macos-latest
            rid: osx-x64
          - platform: macos-latest
            rid: osx-arm64
    runs-on: ${{ matrix.platform }}

    env:
      FILE_VERSION: ${{ github.ref_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore SCSA/SCSA.csproj --runtime ${{ matrix.rid }}

    - name: Publish
      run: |
        dotnet publish SCSA/SCSA.csproj -c Release -r ${{ matrix.rid }} --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish
        cd publish
        ZIP_NAME=SCSA-${{ matrix.rid }}-${FILE_VERSION}.zip
        if [ "$RUNNER_OS" == "Windows" ]; then
          powershell -Command "Compress-Archive -Path * -DestinationPath ../$ZIP_NAME"
        else
          zip -r ../$ZIP_NAME ./*
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.rid }}-binary
        path: SCSA-${{ matrix.rid }}-${{ env.FILE_VERSION }}.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: '*-binary'

    - name: Verify files
      run: find artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: artifacts/*/*.zip
        body: |
          feat: Enhanced IQ Correction Algorithm Configuration and Test Data Simulation

          ## 🚀 New Features
          
          ### IQ Correction Algorithm System Enhancement
          - **Advanced IQ Correction Parameters**: Expanded from simple orthogonality correction switch to comprehensive IQ correction algorithm configuration
          - **Dual Mode Support**: Added automatic/manual mode selection for IQ correction algorithm
          - **Precision Control**: Introduced floating-point correction value parameter for fine-tuning
          - **Parameter Address Optimization**: Reorganized parameter type definitions (OrthogonalityCorrectionSwitch: 0x10000004, OrthogonalityCorrectionMode: 0x1000000C, OrthogonalityCorrectionValue: 0x1000000D)
          
          ### Test Environment Improvements
          - **Simulated Device Status**: Added fixed simulation data for TEC NTC temperature (999), board temperature (22.22°C), and PD current (100.12)
          - **Enhanced Testing Reliability**: Provides stable mock data for development and validation
          
          ## 🔧 Technical Improvements
          - **Parameter System Refactoring**: Updated serialization/deserialization logic for new IQ correction parameter types
          - **Type Safety Enhancement**: Improved parameter type mapping and validation
          - **Protocol Documentation Sync**: Updated communication protocol documentation to reflect parameter changes
          
          ## 📚 Documentation
          - **Communication Protocol Update**: Synchronized protocol documentation with new parameter definitions
          - **Parameter Reference**: Added comprehensive parameter address mapping and value ranges
