name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # 必须要有 Release 写入权限

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        include:
          - platform: ubuntu-latest
            rid: linux-x64
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: |
        dotnet restore SCSA/SCSA.csproj --runtime ${{ matrix.rid }}
        dotnet publish SCSA/SCSA.csproj -c Release -r ${{ matrix.rid }} -o publish

    - name: Zip artifacts
      run: |
        cd publish
        zip -r ../${{ matrix.rid }}.zip ./*  # 直接压缩 publish 目录内容

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.rid }}-binary  # 关键！加 -binary 后缀区分源码
        path: ${{ matrix.rid }}.zip    # 直接上传压缩包

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: '*-binary'  # 只下载编译产物

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          artifacts/*/*.zip  # 递归匹配所有子目录的 zip
